module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  better_field_descriptions: 0
  block: 0
  block_content: 0
  breakpoint: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  ckeditor: 0
  coffee: 0
  config: 0
  config_update: 0
  config_update_ui: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  entity: 0
  entity_browser: 0
  entity_reference_revisions: 0
  externalauth: 0
  features: 0
  features_ui: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  image: 0
  link: 0
  linkit: 0
  media_entity: 0
  menu_link_content: 0
  menu_ui: 0
  module_filter: 0
  node: 0
  options: 0
  override_node_options: 0
  page_cache: 0
  paragraphs: 0
  path: 0
  quickedit: 0
  responsive_image: 0
  search: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  user: 0
  vertical_tabs_config: 0
  views: 0
  views_ui: 0
  pathauto: 1
theme:
  bootstrap: 0
  stable: 0
  classy: 0
  seven: 0
  cwd_base_bootstrap: 0
  cwd_admin: 0
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
