vertical_tabs_config_options: 1
vertical_tabs_config_menu: 2
vertical_tabs_config_revision_information: 3
vertical_tabs_config_path_settings: 4
vertical_tabs_config_author: 5
vertical_tabs_config_book: 6
vertical_tabs_config_ds_switch_view_mode: 7
_core:
  default_config_hash: 5pBXGrhCu5OEK8eoeKYjp2MSgWaJ1eDDN3gZYl_0JF0
